name: Tracker
version: 3
main: com.example.discordlocation.DiscordLocationPlugin
api-version: 1.21
author: Juice, Rahul, Ankit
description: Saves player information and saves you the trouble of copy pasting! Has Discord functionality built in.

commands:
  sendlocation:
    description: Send your current location and biome to Discord
    usage: /sendlocation [note]
    aliases: [loc, location, log]
    permission: discordlocation.send
    permission-message: §cYou don't have permission to use this command!

  listlocations:
    description: List all your saved locations
    usage: /listlocations
    aliases: [locs, locations, mylocations]
    permission: discordlocation.list
    permission-message: §cYou don't have permission to use this command!

  deletelocation:
    description: Delete a saved location by ID
    usage: /deletelocation <id>
    aliases: [delloc, removeloc]
    permission: discordlocation.delete
    permission-message: §cYou don't have permission to use this command!

  renamelocation:
    description: Rename a saved location
    usage: /renamelocation <id/name> <newname>
    aliases: [renloc, renameloc]
    permission: discordlocation.rename
    permission-message: §cYou don't have permission to use this command!

  trackerreload:
    description: Reload the plugin configuration
    usage: /discordlocationreload
    aliases: [dlreload, locreload]
    permission-message: §cYou don't have permission to use this command!

  sharelocation:
    description: Share a saved location with another player
    usage: /sharelocation <id/name> <player>
    aliases: [shareloc]
    permission: discordlocation.share
    permission-message: §cYou don't have permission to use this command!

  acceptshare:
    description: Accept a shared location
    usage: /acceptshare <sender>

  declineshare:
    description: Decline a shared location
    usage: /declineshare <sender>

  confirmsend:
    description: Confirm sending location to Discord
    usage: /confirmsend

  cancelsend:
    description: Cancel sending location to Discord
    usage: /cancelsend

permissions:
  discordlocation.*:
    description: Gives access to all DiscordLocation commands
    children:
      discordlocation.send: true
      discordlocation.list: true
      discordlocation.delete: true
      discordlocation.reload: true
      discordlocation.rename: true
      discordlocation.share: true

  discordlocation.send:
    description: Allows players to send their location to Discord
    default: op

  discordlocation.list:
    description: Allows players to list their saved locations
    default: op

  discordlocation.delete:
    description: Allows players to delete their saved locations
    default: op

  discordlocation.reload:
    description: Allows reloading the plugin configuration
    default: op

  discordlocation.rename:
    description: Allows players to rename their saved locations
    default: op

  discordlocation.share:
    description: Allows players to share their saved locations
    default: op